// ── Tilføj nye byer her ───────────────────────────────────────────────────
// Tilføj blot en ny linje: { value: "by-slug", label: "Bynavn" }
// Det er alt der skal til — ingen andre ændringer nødvendige.

export const CITIES = [
{ value: "koebenhavn",      label: "København" },
{ value: "aarhus",          label: "Aarhus" },
{ value: "odense",          label: "Odense" },
{ value: "aalborg",         label: "Aalborg" },
{ value: "esbjerg",         label: "Esbjerg" },
{ value: "horsens",         label: "Horsens" },
{ value: "randers",         label: "Randers" },
{ value: "kolding",         label: "Kolding" },
{ value: "vejle",           label: "Vejle" },
{ value: "roskilde",        label: "Roskilde" },
{ value: "silkeborg",       label: "Silkeborg" },
{ value: "herning",         label: "Herning" },
{ value: "hoersholm",       label: "Hørsholm" },
{ value: "helsingoer",      label: "Helsingør" },
{ value: "naestved",        label: "Næstved" },
{ value: "viborg",          label: "Viborg" },
{ value: "fredericia",      label: "Fredericia" },
{ value: "koege",           label: "Køge" },
{ value: "taastrup",        label: "Taastrup" },
{ value: "holstebro",       label: "Holstebro" },
{ value: "hilleroed",       label: "Hillerød" },
{ value: "slagelse",        label: "Slagelse" },
{ value: "holbaek",         label: "Holbæk" },
{ value: "soenderborg",     label: "Sønderborg" },
{ value: "svendborg",       label: "Svendborg" },
{ value: "hjoerring",       label: "Hjørring" },
{ value: "noerresundby",    label: "Nørresundby" },
{ value: "oelstykke",       label: "Ølstykke-Stenløse" },
{ value: "ringsted",        label: "Ringsted" },
{ value: "frederikshavn",   label: "Frederikshavn" },
{ value: "haderslev",       label: "Haderslev" },
{ value: "smoerumnedre",    label: "Smørumnedre" },
{ value: "birkerod",        label: "Birkerød" },
{ value: "farum",           label: "Farum" },
{ value: "skanderborg",     label: "Skanderborg" },
{ value: "skive",           label: "Skive" },
{ value: "solroed_strand",  label: "Solrød Strand" },
{ value: "hedehusene",      label: "Hedehusene" },
{ value: "nyborg",          label: "Nyborg" },
{ value: "frederikssund",   label: "Frederikssund" },
{ value: "ikast",           label: "Ikast" },
{ value: "middelfart",      label: "Middelfart" },
{ value: "lilleroed",       label: "Lillerød" },
{ value: "nykoebing_falster", label: "Nykøbing Falster" },
{ value: "aabenraa",        label: "Aabenraa" },
{ value: "kalundborg",      label: "Kalundborg" },
{ value: "varde",           label: "Varde" },
{ value: "korsoer",         label: "Korsør" },
{ value: "grenaa",          label: "Grenaa" },
{ value: "odder",           label: "Odder" },
{ value: "roenne",          label: "Rønne" },
{ value: "hedensted",       label: "Hedensted" },
{ value: "thisted",         label: "Thisted" },
{ value: "vaerloese",       label: "Værløse" },
{ value: "haslev",          label: "Haslev" },
{ value: "frederiksvaerk",  label: "Frederiksværk" },
{ value: "broenderslev",    label: "Brønderslev" },
{ value: "hobro",           label: "Hobro" },
{ value: "dragoer",         label: "Dragør" },
{ value: "nakskov",         label: "Nakskov" },
{ value: "vordingborg",     label: "Vordingborg" },
{ value: "jyllinge",        label: "Jyllinge" },
{ value: "vejen",           label: "Vejen" },
{ value: "lystrup",         label: "Lystrup" },
{ value: "helsinge",        label: "Helsinge" },
{ value: "struer",          label: "Struer" },
{ value: "stoevring",       label: "Støvring" },
{ value: "humlebaek",       label: "Humlebæk" },
{ value: "ringkoebing",     label: "Ringkøbing" },
{ value: "grindsted",       label: "Grindsted" },
{ value: "beder_malling",   label: "Beder-Malling" },
{ value: "galten",          label: "Galten" },
{ value: "saeby",           label: "Sæby" },
{ value: "fredensborg",     label: "Fredensborg" },
{ value: "nykoebing_mors",  label: "Nykøbing Mors" },
{ value: "nivaa",           label: "Nivå" },
{ value: "aars",            label: "Aars" },
{ value: "hinnerup",        label: "Hinnerup" },
{ value: "loegten",         label: "Løgten" },
{ value: "hundested",       label: "Hundested" },
{ value: "hoerning",        label: "Hørning" },
{ value: "hadsten",         label: "Hadsten" },
{ value: "soroe",           label: "Sorø" },
{ value: "ribe",            label: "Ribe" },
{ value: "svenstrup",       label: "Svenstrup" },
{ value: "skjern",          label: "Skjern" },
{ value: "ry",              label: "Ry" },
{ value: "toender",         label: "Tønder" },
{ value: "billund",         label: "Billund" },
{ value: "ebeltoft",        label: "Ebeltoft" },
{ value: "bjerringbro",     label: "Bjerringbro" },
{ value: "vojens",          label: "Vojens" },
{ value: "hammel",          label: "Hammel" },
{ value: "brande",          label: "Brande" },
{ value: "skagen",          label: "Skagen" },
{ value: "bramming",        label: "Bramming" },
{ value: "slangerup",       label: "Slangerup" },
{ value: "ringe",           label: "Ringe" },
{ value: "faaborg",         label: "Faaborg" },
{ value: "aabybro",         label: "Aabybro" },
] as const;

export type CityValue = (typeof CITIES)[number]["value"];

export function getCityLabel(value: string): string {
  return CITIES.find(c => c.value === value)?.label ?? value;
}
